const DB_KEY='zw_chain_demo_v3';
const LOGIN_KEY='zw_login_v3';
const COMPANY='中微区块链技术（深圳）有限公司';

const defaultDb=()=>({users:[],authorizations:[],records:[]});
const db=()=>{try{return JSON.parse(localStorage.getItem(DB_KEY))||defaultDb()}catch{return defaultDb()}};
const save=d=>localStorage.setItem(DB_KEY,JSON.stringify(d));
const currentPhone=()=>localStorage.getItem(LOGIN_KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const maskPhone=s=>s?`${s.slice(0,3)}****${s.slice(-4)}`:'-';
const maskId=s=>s?`${s.slice(0,3)}***********${s.slice(-4)}`:'-';
const now=()=>new Date().toLocaleString('zh-CN',{hour12:false});
const uid=()=>crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
async function sha256(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2800)}
function loggedUser(){const p=currentPhone();return db().users.find(u=>u.phone===p)||null}
function nav(){const n=document.getElementById('navAccount'),u=loggedUser();n.innerHTML=u?`<div class="user-pill"><span class="avatar">${esc(u.name.slice(0,1))}</span><a href="#center">${esc(u.name)}</a></div><button class="btn ghost" onclick="logout()">退出</button>`:`<a href="#login">登录</a><a class="btn" href="#register">立即注册</a>`}
function shell(content){document.getElementById('main').innerHTML=content;window.scrollTo({top:0,behavior:'smooth'});nav()}
function home(){shell(`<section class="hero"><div class="hero-inner"><div><div class="eyebrow">${COMPANY}</div><h1>让每一次授权<br>都有清晰记录</h1><p>面向个人及企业用户的数字存证、授权管理与信息验证展示平台。以清晰的授权流程、可验证的数据指纹和统一的记录管理，呈现可信数据服务的完整产品链路。</p><div class="hero-actions"><a class="btn" href="#register">立即注册</a><a class="btn ghost" href="#verify">验证存证</a></div><div class="notice-line"><i class="dot"></i>互联网展示版 · 当前数据仅保存在本地浏览器</div></div><div class="hero-visual"><div class="visual-card"><div class="eyebrow" style="color:#8fb0ff">TRUSTED DATA</div><h3 class="visual-title">数字存证工作台</h3><p class="visual-copy">注册 → 阅读协议 → 自主授权 → 生成存证 → 在线验证</p><div class="chain-row"><div class="node active">01</div><div class="connector"></div><div class="node">02</div><div class="connector"></div><div class="node">03</div><div class="connector"></div><div class="node">04</div></div><div class="visual-meta"><div class="meta-box"><small>数据指纹</small><b>SHA-256</b></div><div class="meta-box"><small>授权记录</small><b>可追溯</b></div></div></div></div></div></section>
<section id="services" class="section"><div class="section-head"><div><div class="eyebrow">OUR SERVICES</div><h2>一套完整的用户服务流程</h2></div><p>从账户建立到授权、存证和验证，每一步均有清晰页面承接，更接近正式商业平台的产品体验。</p></div><div class="service-grid"><div class="service-card"><div class="service-icon">01</div><h3>用户注册</h3><p>填写手机号、姓名及身份证号码，建立个人演示账户。</p></div><div class="service-card"><div class="service-icon">02</div><h3>授权管理</h3><p>注册前明确展示用户服务协议和隐私政策，由用户自主选择。</p></div><div class="service-card"><div class="service-icon">03</div><h3>数字存证</h3><p>根据用户授权操作生成演示存证编号及 SHA-256 数据指纹。</p></div><div class="service-card"><div class="service-icon">04</div><h3>存证验证</h3><p>通过编号查询记录状态、时间及数据指纹，形成验证闭环。</p></div></div></section>
<section class="flow"><div class="container"><div class="flow-grid"><div class="flow-step"><b>STEP 01</b><h3>创建账户</h3><p>手机号 + 姓名 + 身份证号</p></div><div class="flow-step"><b>STEP 02</b><h3>确认授权</h3><p>阅读并勾选协议及隐私政策</p></div><div class="flow-step"><b>STEP 03</b><h3>生成存证</h3><p>形成编号与数据指纹</p></div><div class="flow-step"><b>STEP 04</b><h3>公开验证</h3><p>输入存证编号即可验证演示记录</p></div></div></div></section>
<section id="verify" class="verify-section"><div class="verify-box"><div><div class="eyebrow" style="color:#8fb0ff">VERIFY</div><h2 style="font-size:34px;margin:7px 0">存证验证</h2><p>输入平台生成的演示存证编号，查看记录状态与数据指纹。未登录也可以进行公开验证。</p></div><div class="verify-panel"><label style="font-size:12px;font-weight:700;display:block;margin-bottom:7px">存证编号</label><div class="verify-form"><input class="input" id="verifyId" placeholder="例如：ZW20260831-AB12CD34" autocomplete="off"><button class="btn" onclick="verifyRecord()">立即验证</button></div><div id="verifyResult" class="verify-result"></div></div></div></section>
<section id="about" class="section"><div class="about-grid"><div class="about-card"><div class="eyebrow">ABOUT PLATFORM</div><h2>${COMPANY}</h2><p>中微链证以数字存证、用户授权与信息验证为产品展示方向，通过互联网展示版 MVP 呈现从用户注册到存证验证的完整服务链路。</p><div class="tag-list"><span class="tag">数字存证</span><span class="tag">授权管理</span><span class="tag">数据指纹</span><span class="tag">在线验证</span></div></div><div class="about-card"><h3>当前版本说明</h3><p>本版本部署于 GitHub Pages，属于纯前端演示项目。注册数据、授权记录和演示存证均使用浏览器 LocalStorage 保存，不连接真实业务数据库，不进行真实身份核验，也未接入真实区块链节点。</p><a class="btn secondary" href="#privacy">查看隐私政策</a></div></div></section>`)}

function registerPage(){shell(`<div class="auth-shell"><div class="form-card"><div class="form-top"><div class="eyebrow">CREATE ACCOUNT</div><h1>创建您的平台账户</h1><p>完成基础信息填写后，阅读并确认相关协议，即可进入用户中心。</p></div><div class="steps"><div class="step active" id="s1"><span class="step-num">1</span><span>填写信息</span></div><div class="step" id="s2"><span class="step-num">2</span><span>确认协议</span></div><div class="step" id="s3"><span class="step-num">3</span><span>注册完成</span></div></div><div id="regBody" class="form-body"></div></div></div>`);renderRegStep(1)}
function renderRegStep(step){const b=document.getElementById('regBody');if(!b)return;document.querySelectorAll('.step').forEach((e,i)=>{e.classList.toggle('active',i<step);e.classList.toggle('done',i<step-1)});if(step===1){b.innerHTML=`<div class="security-note">🔒 <span>本版本为互联网展示版。为保护个人隐私，请勿输入真实身份证号码或其他敏感个人信息。</span></div><div class="field"><label>手机号码</label><input class="input" id="regPhone" inputmode="numeric" maxlength="11" placeholder="请输入11位手机号码"></div><div class="field"><label>姓名</label><input class="input" id="regName" maxlength="20" placeholder="请输入姓名"></div><div class="field"><label>身份证号码</label><input class="input" id="regId" maxlength="18" placeholder="请输入18位身份证号码（演示请使用虚拟号码）"></div><div class="form-actions"><button class="btn full" onclick="regNext()">下一步</button></div><p style="font-size:12px;color:#98a2b3;text-align:center;margin:18px 0 0">已有账户？<a href="#login" style="color:#2457d6;text-decoration:none">立即登录</a></p>`}else if(step===2){b.innerHTML=`<div class="security-note">ⓘ <span>请先完整阅读以下文件。实际生产环境应根据真实业务场景、处理目的和数据范围制定正式文本。</span></div><div class="consent-box"><div class="consent-row"><input id="regAgree" type="checkbox"><span>我已阅读并理解 <a href="#agreement">《用户服务协议》</a> 和 <a href="#privacy">《隐私政策》</a>，并同意按照协议约定使用平台服务。</span></div></div><div class="consent-box"><div class="consent-row"><input id="regSensitive" type="checkbox"><span>我知悉身份证号码属于敏感个人信息；本展示版不会将所填信息上传至服务端，仅在当前浏览器本地保存演示数据。</span></div></div><div class="form-actions"><button class="btn ghost" onclick="renderRegStep(1)">返回修改</button><button class="btn full" onclick="finishRegister()">同意并完成注册</button></div>`}else{const u=loggedUser();b.innerHTML=`<div class="success-view"><div class="success-icon">✓</div><h2>注册成功</h2><p>您的演示账户已经创建，可以进入用户中心查看授权和存证功能。</p><div style="display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:22px"><a class="btn" href="#center">进入用户中心</a><a class="btn ghost" href="#home">返回首页</a></div><p style="font-size:11px;margin-top:20px">当前账户：${esc(maskPhone(u?.phone||''))}</p></div>`}}
function regNext(){const phone=document.getElementById('regPhone').value.trim(),name=document.getElementById('regName').value.trim(),id=document.getElementById('regId').value.trim();if(!/^1\d{10}$/.test(phone))return toast('请输入正确的11位手机号码');if(!name||name.length<2)return toast('请输入正确的姓名');if(!/^\d{17}[\dXx]$/.test(id))return toast('请输入18位身份证号码（演示可使用虚拟号码）');const d=db();if(d.users.some(u=>u.phone===phone))return toast('该手机号已注册，请直接登录');if(d.users.some(u=>u.id.toUpperCase()===id.toUpperCase()))return toast('该身份证号已注册');window.__reg={phone,name,id};renderRegStep(2)}
function finishRegister(){if(!document.getElementById('regAgree')?.checked)return toast('请阅读并同意《用户服务协议》和《隐私政策》');if(!document.getElementById('regSensitive')?.checked)return toast('请确认已知悉敏感个人信息处理提示');const x=window.__reg;if(!x)return renderRegStep(1);const d=db();d.users.push({uid:uid(),phone:x.phone,name:x.name,id:x.id,createdAt:now(),consentAt:now(),consentVersion:'2026-08-31'});save(d);localStorage.setItem(LOGIN_KEY,x.phone);renderRegStep(3);nav();toast('注册成功')}

function loginPage(){shell(`<div class="auth-shell"><div class="form-card"><div class="form-top"><div class="eyebrow">SIGN IN</div><h1>登录中微链证</h1><p>使用注册时的手机号与身份证号码进入用户中心。</p></div><div class="form-body" style="padding-top:28px"><div class="security-note">🔒 <span>展示版采用免验证码、免密码的简化登录流程，仅用于产品体验演示。</span></div><div class="field"><label>手机号码</label><input class="input" id="loginPhone" inputmode="numeric" maxlength="11" placeholder="请输入注册手机号"></div><div class="field"><label>身份证号码</label><input class="input" id="loginId" maxlength="18" placeholder="请输入注册时使用的身份证号码"></div><button class="btn full" onclick="login()">登录</button><p style="font-size:12px;color:#98a2b3;text-align:center;margin-top:18px">还没有账户？<a href="#register" style="color:#2457d6;text-decoration:none">立即注册</a></p><div class="consent-box">提示：生产环境不建议仅凭手机号和身份证号完成身份认证，应根据实际业务采用更安全的认证与授权机制。</div></div></div></div>`)}
function login(){const phone=document.getElementById('loginPhone')?.value.trim(),id=document.getElementById('loginId')?.value.trim();if(!/^1\d{10}$/.test(phone))return toast('请输入正确的手机号码');if(!/^\d{17}[\dXx]$/.test(id))return toast('请输入18位身份证号码');const u=db().users.find(x=>x.phone===phone&&x.id.toUpperCase()===id.toUpperCase());if(!u)return toast('手机号或身份证号码不匹配');localStorage.setItem(LOGIN_KEY,u.phone);toast('登录成功');location.hash='#center'}
function logout(){localStorage.removeItem(LOGIN_KEY);toast('已安全退出');location.hash='#home'}

function center(){const u=loggedUser();if(!u){location.hash='#login';return}const d=db(),a=d.authorizations.filter(x=>x.phone===u.phone),r=d.records.filter(x=>x.phone===u.phone);shell(`<div class="dashboard-shell"><div class="dash-head"><div><div class="eyebrow">USER CENTER</div><h1>用户中心</h1><p>账户信息、授权记录和我的存证统一管理。</p></div><button class="btn danger" onclick="logout()">退出登录</button></div><div class="identity-card"><div class="identity-main"><div class="big-avatar">${esc(u.name.slice(0,1))}</div><div><small>欢迎回来</small><h2>${esc(u.name)}</h2><small>${esc(maskPhone(u.phone))}</small></div></div><div><small>账户状态</small><div style="font-weight:700;margin-top:4px">● 正常</div></div></div><div class="stats"><div class="stat-card"><small>我的存证</small><strong>${r.length}</strong></div><div class="stat-card"><small>授权记录</small><strong>${a.length}</strong></div><div class="stat-card"><small>注册时间</small><strong style="font-size:16px">${esc(u.createdAt)}</strong></div></div><div class="dash-grid"><div class="dash-card"><h2>账户信息</h2><p>以下信息仅用于当前演示环境展示，并已做脱敏处理。</p><div class="auth-item"><span>手机号码</span><b>${esc(maskPhone(u.phone))}</b></div><div class="auth-item"><span>姓名</span><b>${esc(u.name)}</b></div><div class="auth-item"><span>身份证号码</span><b>${esc(maskId(u.id))}</b></div><div class="auth-item"><span>协议版本</span><b>${esc(u.consentVersion||'-')}</b></div></div><div class="dash-card"><h2>授权记录</h2><p>记录您主动确认授权的时间和协议版本。</p>${a.map(x=>`<div class="auth-item"><span>${esc(x.time)}<br><small>${esc(x.consentVersion)}</small></span><span>已授权</span></div>`).join('')||'<div class="empty">暂无授权记录</div>'}<div style="margin-top:14px"><a class="btn secondary" href="#agreement">查看用户服务协议</a> <a class="btn secondary" href="#privacy">查看隐私政策</a></div></div></div><div class="dash-card" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><h2>我的存证</h2><p>每次确认服务授权后可生成一条演示存证。</p></div><a class="btn" href="#authorize">新增授权</a></div>${r.map(x=>`<div class="record"><div class="record-main"><b>${esc(x.id)}</b><small>${esc(x.time)}</small></div><span class="record-status">有效</span><a href="#record-${encodeURIComponent(x.id)}">查看详情</a></div>`).join('')||'<div class="empty">暂无存证记录，完成一次授权后即可生成。</div>'}</div></div>`)}
function authorize(){const u=loggedUser();if(!u){location.hash='#login';return}shell(`<div class="auth-shell"><div class="form-card"><div class="form-top"><div class="eyebrow">AUTHORIZATION</div><h1>服务授权确认</h1><p>请在充分阅读协议与隐私政策后，自主决定是否继续。</p></div><div class="form-body" style="padding-top:26px"><div class="policy-alert">本页面仅用于展示“告知—阅读—确认—记录”的产品流程。当前版本不会向外部服务提交您的信息。</div><div class="consent-box"><b>您将确认的内容</b><ul><li>已阅读并理解《用户服务协议》</li><li>已阅读并理解《隐私政策》</li><li>同意在展示版规定范围内记录本次授权操作</li></ul><div style="margin-top:12px"><a href="#agreement">阅读用户服务协议 →</a>　<a href="#privacy">阅读隐私政策 →</a></div></div><label class="consent-row" style="font-size:13px"><input id="authAgree" type="checkbox"><span>我已阅读上述文件，并自愿确认本次服务授权。</span></label><button class="btn full" style="margin-top:18px" onclick="createEvidence()">确认授权并生成存证</button></div></div></div>`)}
async function createEvidence(){if(!document.getElementById('authAgree')?.checked)return toast('请先阅读并勾选授权确认');const u=loggedUser();if(!u)return location.hash='#login';const d=db(),time=now();const hash=await sha256(`${u.phone}|${u.name}|${u.id}|${time}|${uid()}`);const id='ZW'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+hash.slice(0,8).toUpperCase();d.authorizations.push({id:uid(),phone:u.phone,time,consentVersion:u.consentVersion||'2026-08-31'});d.records.push({id,phone:u.phone,time,hash,status:'有效',type:'用户授权演示存证'});save(d);toast('授权已记录，存证已生成');location.hash='#record-'+encodeURIComponent(id)}
function recordDetail(id){const r=db().records.find(x=>x.id===decodeURIComponent(id));if(!r){location.hash='#center';return}const u=db().users.find(x=>x.phone===r.phone);shell(`<div class="detail-shell"><a class="back" href="#center">← 返回用户中心</a><div class="detail-card"><div class="eyebrow">EVIDENCE DETAIL</div><h1>存证详情</h1><div class="detail-grid"><div class="detail-item"><small>存证编号</small><strong>${esc(r.id)}</strong></div><div class="detail-item"><small>存证状态</small><strong style="color:#15803d">● ${esc(r.status)}</strong></div><div class="detail-item"><small>存证时间</small><strong>${esc(r.time)}</strong></div><div class="detail-item"><small>用户</small><strong>${esc(u?.name||'-')}</strong></div></div><div class="hash-box"><small>SHA-256 数据指纹</small><code>${esc(r.hash)}</code></div><div class="demo-warning">当前记录由浏览器本地生成，仅用于展示存证流程；未连接真实区块链节点、生产数据库或第三方权威存证机构，因此不应将本页面作为真实业务存证或身份认证依据。</div><div style="margin-top:18px"><a class="btn secondary" href="#verify">前往公开验证</a></div></div></div>`)}
function verifyRecord(){const id=document.getElementById('verifyId')?.value.trim();const r=db().records.find(x=>x.id===id),el=document.getElementById('verifyResult');if(!id){el.innerHTML='<div class="result bad">请输入存证编号。</div>';return}el.innerHTML=r?`<div class="result ok"><b>✓ 演示存证记录有效</b><br>编号：${esc(r.id)}<br>时间：${esc(r.time)}<br>状态：${esc(r.status)}<br>数据指纹：${esc(r.hash.slice(0,18))}……${esc(r.hash.slice(-18))}<br><small>提示：这是本浏览器生成的展示记录，并非真实区块链上链数据。</small></div>`:'<div class="result bad">未查询到对应记录，请检查存证编号。</div>'}

function agreement(){shell(`<div class="policy-shell"><div class="policy-card"><div class="eyebrow">LEGAL DOCUMENT</div><h1>用户服务协议</h1><div class="policy-meta">运营主体：${COMPANY}　|　更新日期：2026年8月31日　|　生效日期：2026年8月31日</div><div class="policy-alert">重要提示：请您在注册或使用平台服务前认真阅读本协议，特别关注账户使用、用户授权、个人信息保护及责任限制等条款。</div><div class="policy-toc"><a href="#agreement-top">协议说明</a><a href="#agreement-account">账户</a><a href="#agreement-service">服务</a><a href="#agreement-user">用户行为</a><a href="#agreement-ip">知识产权</a><a href="#agreement-change">协议变更</a><a href="#agreement-contact">联系我们</a></div><h2 id="agreement-top">一、协议说明</h2><p>欢迎使用中微链证数字存证与授权服务平台。本协议由${COMPANY}（以下简称“平台”）与使用平台服务的用户（以下简称“用户”）共同订立，用于约定账户注册、平台展示、授权记录、存证查询以及相关页面服务的基本规则。</p><p>用户点击“注册”“登录”“确认授权”等按钮，或以其他方式使用平台服务前，应阅读并理解本协议及与个人信息处理有关的《隐私政策》。如用户不同意相关内容，应停止注册或使用对应服务。</p><h2 id="agreement-account">二、账户注册与使用</h2><p>用户注册时应按照页面要求提供真实、准确、完整且合法的信息。用户不得冒用他人身份，不得提供虚假资料，不得利用平台实施欺诈、侵害他人权益或其他违法违规活动。</p><p>用户应合理使用自己的账户，不得以任何方式转让、出租、出借或非法获取他人账户。发现账户存在异常使用情形时，应及时采取必要措施并通过正式渠道联系平台。</p><h2 id="agreement-service">三、平台服务</h2><p>平台可根据实际产品规划提供用户账户、授权管理、数字存证展示、存证编号验证等服务。具体服务内容以实际页面展示及双方约定为准。</p><p>存证功能可对特定操作信息生成数据摘要、时间信息和唯一编号，用于展示数据完整性校验等技术能力。具体存证技术、保存期限、法律效力及第三方公证或司法采信情况，应以实际业务方案及适用法律法规为准。</p><h2>四、用户授权</h2><p>平台在需要用户作出授权决定时，应通过页面对处理目的、处理方式、处理范围、必要性及相关权利进行清晰说明。用户应在充分阅读相关文件后自主决定是否授权。</p><p>用户可以根据平台实际提供的功能查询其授权记录。对于依法需要取得单独同意或其他法定授权形式的处理活动，平台应按照适用法律法规另行履行相应要求。</p><h2 id="agreement-user">五、用户行为规范</h2><ul><li>不得提交违法、侵权、虚假或恶意内容；</li><li>不得利用平台攻击、干扰、破坏网络或系统安全；</li><li>不得未经他人合法授权提交、查询或处理他人个人信息；</li><li>不得绕过技术措施、批量抓取或滥用平台服务；</li><li>不得实施其他违反法律法规、公序良俗或本协议的行为。</li></ul><h2 id="agreement-ip">六、知识产权</h2><p>平台页面、软件程序、界面设计、商标、文字、图形、数据结构及其他相关内容的知识产权依法受到保护。未经合法授权，任何主体不得擅自复制、修改、传播、反向工程或用于与平台业务无关的商业活动。</p><h2>七、数据安全与隐私保护</h2><p>涉及个人信息处理的实际生产系统，应根据业务场景采取访问控制、加密传输、加密或去标识化存储、权限管理、日志审计、数据生命周期管理等必要安全措施，并依法保障用户个人信息权益。</p><h2>八、服务中断与免责声明</h2><p>因网络故障、系统维护、第三方服务异常、不可抗力等原因造成服务暂时中断的，平台将在合理范围内采取恢复措施。平台服务的具体功能、可用范围及技术能力以实际页面及服务规则为准。</p><h2 id="agreement-change">九、协议变更</h2><p>平台可能因产品功能、业务模式或法律法规变化对本协议进行更新。协议更新后将在页面展示最新版本及更新时间；涉及用户重大权益的变更，平台将依法履行相应的告知义务。</p><h2>十、适用法律与争议解决</h2><p>本协议的订立、履行及争议解决适用中华人民共和国大陆地区现行有效的法律法规。具体争议解决方式以实际正式协议及适用法律规定为准。</p><h2 id="agreement-contact">十一、联系我们</h2><p>运营主体：${COMPANY}。正式生产环境应在本页面公布有效的客服、联系地址、个人信息权益处理渠道等必要信息。</p></div></div>`)}
function privacy(){shell(`<div class="policy-shell"><div class="policy-card"><div class="eyebrow">PRIVACY DOCUMENT</div><h1>隐私政策</h1><div class="policy-meta">运营主体：${COMPANY}　|　更新日期：2026年8月31日　|　生效日期：2026年8月31日</div><div class="policy-alert">重要提示：身份证号码属于敏感个人信息。身份证号码属于敏感个人信息，请您仅在明确了解处理目的、范围和必要性的情况下提供。</div><div class="policy-toc"><a href="#privacy-collect">收集信息</a><a href="#privacy-use">使用目的</a><a href="#privacy-sensitive">敏感信息</a><a href="#privacy-share">共享与委托</a><a href="#privacy-rights">用户权利</a><a href="#privacy-retention">保存与删除</a><a href="#privacy-security">安全</a><a href="#privacy-contact">联系我们</a></div><h2 id="privacy-collect">一、我们收集哪些信息</h2><p>用户在注册及使用相关服务时，可以根据页面要求主动填写手机号码、姓名和身份证号码，用于账户注册、登录、身份关联、授权记录及相关服务。我们遵循最小必要原则，仅处理实现具体功能所必需的个人信息。</p><h2 id="privacy-use">二、我们如何使用个人信息</h2><p>在真实业务中，个人信息可能用于账户建立与管理、身份信息关联、用户授权记录、服务通知、安全管理、存证记录展示及依法履行相关义务。平台不应将个人信息用于超出告知范围的目的；如改变处理目的、方式或范围，应依法履行相应告知和授权程序。</p><h2 id="privacy-sensitive">三、敏感个人信息处理</h2><p>身份证号码属于敏感个人信息。处理敏感个人信息应具有特定目的和充分必要性，并依法履行更严格的告知、同意、风险评估、安全保护等义务。正式生产环境不应以本展示版的简化流程替代法律法规要求的身份认证或授权机制。</p><h2>四、个人信息来源</h2><p>原则上，平台通过用户在页面主动填写、主动提交或主动操作的方式获取相关信息。未经合法授权，不应通过非法购买、交换、爬取等方式获取个人信息。</p><h2 id="privacy-share">五、共享、委托处理与公开</h2><p>除法律法规要求、用户主动选择的服务或为实现特定服务所必需的情形外，平台原则上不向无关第三方提供个人信息。如涉及委托处理，应依法对受托方进行管理并采取必要的安全保护措施；如涉及公开披露，应具有合法、正当的依据。</p><h2>六、个人信息跨境提供</h2><p>如实际业务涉及向境外提供个人信息，应依据适用法律法规履行相应的个人信息出境合规要求。本展示版不开展实际跨境个人信息处理。</p><h2 id="privacy-retention">七、保存期限与删除</h2><p>实际生产环境应根据处理目的确定最短必要保存期限。达到保存期限后，应依法删除或进行匿名化处理；法律法规另有规定的，从其规定。用户可按照实际平台公布的渠道申请删除或处理其个人信息。</p><h2 id="privacy-security">八、个人信息安全</h2><p>生产系统应根据风险采取HTTPS/TLS、访问权限控制、敏感字段脱敏或加密、密钥管理、操作日志、安全审计、异常监测、备份恢复等措施，并建立个人信息安全事件应急处置机制。</p><p>在具体服务中，我们会根据实际技术架构采取适当的数据存储、访问控制和安全保护措施。</p><h2 id="privacy-rights">九、您的个人信息权利</h2><p>依法处理个人信息时，用户通常依法享有知情、决定、查阅、复制、更正、删除等相关权益，并可依法要求解释个人信息处理规则。正式生产平台应提供清晰、可用的权益申请渠道，并在法律规定期限内处理。</p><h2>十、未成年人保护</h2><p>如实际服务可能涉及未成年人，应按照适用法律法规建立相应的保护机制。涉及敏感个人信息处理时，应采取与未成年人保护要求相匹配的措施。</p><h2>十一、Cookie及类似技术</h2><p>平台可能使用 Cookie、本地存储、SDK 或类似技术，以维持登录状态、保存必要服务设置、保障系统安全及改善服务体验；如相关技术涉及个人信息处理，我们将依法履行相应告知义务。</p><h2>十二、政策更新</h2><p>我们可能根据法律法规、业务功能和安全措施变化更新本政策，并在页面展示最新版本。涉及用户重大权益的变化，将依法履行相应告知义务。</p><h2 id="privacy-contact">十三、个人信息保护相关联系</h2><p>运营主体：${COMPANY}。正式生产环境应在此公布个人信息保护负责人或相关联系渠道、联系地址及用户权益申请方式。</p><h2>十四、其他</h2><p>本政策与平台注册页面、具体服务页面中的隐私说明共同构成个人信息保护规则的一部分。若具体服务对个人信息处理另有特别说明，我们将依法向您进行相应告知并在必要时取得您的授权。</p></div></div>`)}

function render(){const h=location.hash||'#home';if(h==='#home'||h==='#services'||h==='#about'){home();if(h!=='#home')setTimeout(()=>document.querySelector(h)?.scrollIntoView({behavior:'smooth'}),50);return}if(h==='#verify'){home();setTimeout(()=>document.querySelector('#verify')?.scrollIntoView({behavior:'smooth'}),50);return}if(h==='#register')return registerPage();if(h==='#login')return loginPage();if(h==='#center')return center();if(h==='#authorize')return authorize();if(h==='#agreement')return agreement();if(h==='#privacy'||h.startsWith('#privacy#'))return privacy();if(h.startsWith('#record-'))return recordDetail(h.slice(8));home()}
window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',render);render();
